config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :categories
  resources :posts

  root :to => 'sessions#index'

  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  belongs_to :user
  has_many :posts, dependent: :delete_all

  validates :name, presence: true, uniqueness: true

  # ログインユーザーに紐づくカテゴリ一覧を更新順に取得する
  def self.list_for(current_user)
    where(user_id: current_user.id).order(updated_at: :desc).map{ |category| [category.name, category.id] }
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  content     :text(65535)
#  user_id     :integer
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user

  paginates_per 5

  def self.latest_post_time(category)
    order(updated_at: :desc).first.updated_at
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password

  has_many :categories, dependent: :delete_all
  has_many :posts, dependent: :delete_all

  validates :name, presence: true, length: { minimum: 2 }
  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include SessionsHelper

  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :redirect_to_login_path

  def index
    @categories = Category.all
    flash.now[:info] = "まだカテゴリが登録されていません" if @categories.empty?
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "登録しました！"
      redirect_to @category
    else
      flash.now[:danger] = "しっぱいしました"
      render 'new'
    end
  end

  def edit
  end

  def show
    @posts = @category.posts.order(updated_at: :desc).page(params[:page])
  end

  def update
    if @category.update(category_params)
      flash[:success] = "更新しました！"
      redirect_to @category
    else
      flash.now[:danger] = "しっぱいしました"
      render 'edit'
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = "削除しました"
      redirect_to categories_path
    else
      flash.now[:danger] = "しっぱいしました"
      render 'show'
    end
  end

  private
    def category_params
      params.require(:category).permit(:name, :user_id)
    end

    def set_category
      @category = Category.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :redirect_to_login_path

  def index
    @posts = Post.where(user_id: current_user.id).includes(:category).order(updated_at: :desc).page(params[:page])
    flash.now[:info] = "まだ投稿がありません" if @posts.empty?
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "登録しました！"
      redirect_to @post
    else
      flash.now[:danger] = "しっぱいしました"
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def update
    if @post.update(post_params)
      flash[:success] = "更新しました！"
      redirect_to @post
    else
      flash.now[:danger] = "しっぱいしました"
      render 'edit'
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = "削除しました"
      redirect_to posts_path
    else
      flash.now[:danger] = "しっぱいしました"
      render 'show'
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :category_id)
    end

    def set_post
      @post = Post.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "ログインしました！"
      redirect_to user
    else
      flash.now[:danger] = "ログインにしっぱいしました"
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = "ログアウトしました"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :redirect_to_login_path, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "登録しました！"
      redirect_to @user
    else
      flash.now[:danger] = "しっぱいしました"
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def update
    if @user.update(user_params)
      flash[:success] = "更新しました！"
      redirect_to @user
    else
      flash.now[:danger] = "しっぱいしました"
      render 'edit'
    end
  end

  def destroy
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログインしているユーザーを返す
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # ユーザーがログインしていればtrue、それ以外ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_to_login_path
    unless logged_in?
      flash[:info] = "この機能を利用するにはログインが必要です"
      redirect_to login_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category_form.html.erb
<%= form_for category, class: "form-group" do |f| %>
  <%= f.label :name, "カテゴリ名" %>
  <%= f.text_field :name, placeholder: "例）映画", class: "form-control" %><br>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.submit "保存", class: "btn btn-lg btn-success" %>
<% end %>

app/views/categories/edit.html.erb
<h3><%= fa_icon("tag", text: "カテゴリの編集") %></h3>

<%= render 'layouts/error_message', { object: @category } %>

<p class="lead">必要な情報を入力してください。</p>
<%= render 'category_form', { category: @category } %>

app/views/categories/index.html.erb
<h3>
  <%= fa_icon("tags", text: "カテゴリ一覧") %>
  <%= link_to "新規登録", new_category_path, class: "btn btn-success" %>
</h3>

<table class="table">
  <tr>
    <th class="col-xs-1"></th>
    <th class="col-xs-4">カテゴリ名</th>
    <th class="col-xs-2">投稿数</th>
    <th class="col-xs-5">投稿の最終更新日</th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td><%= link_to "編集", edit_category_path(category), class: "btn btn-xs btn-info" %></td>
      <td><%= link_to category.name, category %></td>
      <td><%= category.posts.count %></td>
      <td><%= category.posts.latest_post_time(category) unless category.posts.empty? %></td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h3><%= fa_icon("tag", text: "カテゴリ登録") %></h3>

<%= render 'layouts/error_message', { object: @category } %>

<p class="lead">必要な情報を入力してください。</p>
<%= render 'category_form', { category: @category } %>

app/views/categories/show.html.erb
<h3>
  <%= fa_icon("tag", text: @category.name) %>
  <%= content_tag :div, "投稿数：#{@posts.total_count}" ,class: "badge" %>
  <%= link_to "編集", edit_category_path, class: "btn btn-info" %>
  <%= link_to "削除", @category, method: :delete, data: { confirm: "カテゴリを削除すると、それに紐付く#{@category.posts.count}件の投稿も削除されます。削除して大丈夫ですか？"}, class: "btn btn-warning" %>
</h3>
<hr>

<%= render 'layouts/post', { posts: @posts } %>

app/views/layouts/_error_message.html.erb
<% if object.errors.any? %>
  <p class="text-danger"><%= object.errors.count %>つのエラーがあります。</p>
  <ul>
  <% object.errors.full_messages.each do |error| %>
    <li class="text-danger"><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_post.html.erb
<%= paginate posts %>

<% unless posts.empty? %>
  <% posts.each do |post| %>
    <div class="row">
      <div class="col-sm-12 col-md-12">
        <div class="thumbnail">
          <div class="caption">
            <h4><%= link_to post.title, post %></h4>
            <%= simple_format(post.content) %>
            <hr>
            <%= fa_icon("tag lg") %>&nbsp;<%= link_to post.category.name, post.category %> | <%= post.updated_at %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<%= paginate posts %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mylog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="header clearfix" style="margin: 17px 0px;">
      <nav>
        <ul class="nav nav-pills pull-right">
          <li role="presentation" class="active"><%= link_to "投稿", new_post_path %></li>
          <li><%= link_to "投稿一覧", posts_path, class: "presentation" %></li>
          <li role="presentation"><a href="#">検索</a></li>
          <% if logged_in? %>
            <li class="dropdown">
              <a href='#' class="dropdown-toggle" data-toggle="dropdown">
                <%=  %>アカウント<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "カテゴリ一覧", categories_path %></li>
                <li><%= link_to "プロフィール（設定）", current_user %></li>
                <li class="divider"></li>
                <li><%= link_to "ログアウト", logout_path, method: :delete, data: { confirm: "ログアウトしますか？" } %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "ログイン", login_path %></li>
          <% end %>
        </ul>
      </nav>
      <%= link_to root_path do %>
        <%= image_tag 'logo.png', height: '50' %>
      <% end %>
    </div>
    <div class="jumbotron">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "alert alert-#{key}" %>
      <% end %>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/posts/_post_form.html.erb
<%= form_for post, class: "form-control" do |f| %>
  <%= f.label :title, "タイトル"%>
  <%= f.text_field :title, class: "form-control" %><br>

  <%= f.label :category_id, "カテゴリ" %>
  <%= f.select :category_id, Category.list_for(current_user), { prompt: true }, { class: "form-control" } %><br>

  <%= f.label :content, "内容" %>
  <%= f.text_area :content, class: "form-control" %><br>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.submit "保存", class: "btn btn-lg btn-success" %>
<% end %>

app/views/posts/edit.html.erb
<h3><%= fa_icon("file-text", text: "投稿の編集") %></h3>

<%= render 'layouts/error_message', { object: @post } %>

<p class="lead">必要な情報を入力してください。</p>
<%= render 'post_form', { post: @post } %>

app/views/posts/index.html.erb
<h3>
  <%= fa_icon("file-text", text: "投稿一覧") %>
  <%= content_tag :div, "投稿数：#{@posts.total_count}", class: "badge" %>
  <%= link_to "新規投稿", new_post_path, class: "btn btn-success" %>
</h3>
<hr>

<%= render 'layouts/post', { posts: @posts } %>

app/views/posts/new.html.erb
<h3><%= fa_icon("file-text", text: "新規投稿") %></h3>

<%= render 'layouts/error_message', { object: @post } %>

<p class="lead">必要な情報を入力してください。</p>
<%= render 'post_form', { post: @post } %>

app/views/posts/show.html.erb
<h3>
  <%= fa_icon("file-text", text: @post.title) %>
  <%= link_to "編集", edit_post_path, class: "btn btn-info" %>
  <%= link_to "削除", @post, method: :delete, data: { confirm: "この投稿を削除します。削除して大丈夫ですか？"}, class: "btn btn-warning" %>
</h3>

<table class="table">
  <tr><td><%= simple_format(@post.content) %></td></tr>
  <tr><td><%= fa_icon("tag lg") %>&nbsp;<%= link_to @post.category.name, @post.category %></td></tr>
</table>

app/views/users/_user_form.html.erb
<%= form_for user, class: "form-group" do |f| %>
  <%= f.label :name, "ユーザー名" %>
  <%= f.text_field :name, placeholder: "例）パイン", class: "form-control" %><br>

  <%= f.label :email, "メールアドレス" %>
  <%= f.text_field :email, placeholder: "例）pine0301@example.com", class: "form-control" %><br>

  <%= f.label :password, "パスワード" %>
  <%= f.password_field :password, class: "form-control" %><br>

  <%= f.label :password_confirmation, "パスワード（確認）" %>
  <%= f.password_field :password_confirmation, class: "form-control" %><br>

  <%= f.submit "登録", class: "btn btn-lg btn-success" %>
<% end %>

app/views/users/edit.html.erb
<h3><%= fa_icon("address-book-o", text: "ユーザー情報の修正") %></h3>

<%= render 'layouts/error_message', { object: @user } %>

<p class="lead">必要な情報を入力してください。</p>
<%= render 'user_form', { user: @user } %>

app/views/users/new.html.erb
<h2><%= fa_icon("address-book-o", text: "ユーザー登録") %></h2>

<%= render 'layouts/error_message', { object: @user } %>

<p class="lead">必要な情報を入力してください。</p>
<%= render 'user_form', { user: @user } %>

app/views/users/show.html.erb
<h3>
  <%= fa_icon("address-book-o", text: @user.name) %>
  <%= link_to "編集", edit_user_path, class: "btn btn-info" %>
</h3>

<table class="table">
  <tr>
    <th class="col-xs-3">メールアドレス</th><td><%= @user.email %></td>
  </tr>
</table>